# Generated by Django 5.2.5 on 2025-08-28 18:55

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rol', models.CharField(choices=[('operador', 'Operador'), ('coordinador', 'Coordinador'), ('soporte', 'Soporte'), ('monitor', 'Monitor')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece este usuario.', related_name='usuarios_groups', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuarios_permissions', to='auth.permission', verbose_name='permisos de usuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCoordinador',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_coordinador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilMonitor',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_monitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilSoporte',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_soporte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilOperador',
            fields=[
                ('ci', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('tipo_personal', models.CharField(max_length=50)),
                ('coordinador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='usuarios.perfilcoordinador')),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='usuarios.perfilmonitor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_operador', to=settings.AUTH_USER_MODEL)),
                ('soporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores_asignados', to='usuarios.perfilsoporte')),
            ],
        ),
    ]
