# Generated by Django 5.2.5 on 2025-08-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmonitor',
            name='celular',
            field=models.CharField(default='00000000', max_length=20),
        ),
    ]
