# Generated by Django 5.2.5 on 2025-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilmonitor_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilmonitor',
            name='celular',
            field=models.CharField(max_length=20),
        ),
    ]
