# Generated by Django 5.2.5 on 2025-08-29 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfilmonitor_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiloperador',
            name='coordinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='usuarios.perfilcoordinador'),
        ),
        migrations.AlterField(
            model_name='perfiloperador',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='usuarios.perfilmonitor'),
        ),
        migrations.AlterField(
            model_name='perfiloperador',
            name='soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores_asignados', to='usuarios.perfilsoporte'),
        ),
    ]
