# Generated by Django 5.2.5 on 2025-09-05 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_email_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('provincia', models.CharField(blank=True, default='-', max_length=100)),
                ('municipio', models.CharField(blank=True, default='-', max_length=100)),
                ('localidad', models.CharField(blank=True, default='-', max_length=100)),
                ('recinto', models.CharField(blank=True, default='-', max_length=100)),
                ('mesa1', models.IntegerField(default=0)),
                ('mesa2', models.IntegerField(default=0)),
                ('mesa3', models.IntegerField(default=0)),
                ('mesa4', models.IntegerField(default=0)),
                ('mesa5', models.IntegerField(default=0)),
                ('mesa6', models.IntegerField(default=0)),
                ('mesa7', models.IntegerField(default=0)),
                ('mesa8', models.IntegerField(default=0)),
                ('fecha_transmision', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas_operador', to='usuarios.perfiloperador')),
            ],
        ),
    ]
