# Generated by Django 5.2.5 on 2025-09-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_acta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='id',
        ),
        migrations.AlterField(
            model_name='acta',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
