# Generated by Django 5.2.5 on 2025-09-05 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_acta_id_alter_acta_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='fecha_transmision',
        ),
        migrations.AlterField(
            model_name='acta',
            name='operador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_asignada', to='usuarios.perfiloperador'),
        ),
    ]
