# Generated by Django 5.2.5 on 2025-09-05 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_acta_fecha_transmision_alter_acta_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='operador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_operador', to='usuarios.perfiloperador'),
        ),
    ]
