# Generated by Django 5.2.5 on 2025-09-05 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_acta_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='actas_asignadas',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='fecha_transmision',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
