# Generated by Django 5.2.5 on 2025-09-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_acta_actas_asignadas_acta_fecha_transmision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='fecha_transmision',
        ),
    ]
