# Generated by Django 5.2.5 on 2025-09-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_acta_fecha_transmision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='mesa1',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='mesa2',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='mesa3',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='mesa4',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='mesa5',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='mesa6',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='mesa7',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='mesa8',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
