# Generated by Django 5.2.5 on 2025-09-11 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_acta_mesa1_alter_acta_mesa2_alter_acta_mesa3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=False)),
                ('fecha', models.CharField(blank=True, default='-', max_length=50)),
                ('observacion', models.TextField(blank=True, default='-')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_operador', to='usuarios.perfiloperador')),
            ],
        ),
    ]
