# Generated by Django 5.2.5 on 2025-09-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('fecha', models.CharField(blank=True, default='-', max_length=50)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_adicionales', to='usuarios.perfiloperador')),
            ],
        ),
    ]
