# Generated by Django 5.2.5 on 2025-09-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_observacionadicional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observacionadicional',
            options={'verbose_name': 'observación adicional', 'verbose_name_plural': 'observaciones adicionales'},
        ),
        migrations.CreateModel(
            name='DetalleAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_apk', models.CharField(blank=True, default='-', max_length=100)),
                ('transmitido', models.CharField(blank=True, default='-', max_length=20)),
                ('no_transmitido', models.CharField(blank=True, default='-', max_length=20)),
                ('operador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_adicional', to='usuarios.perfiloperador')),
            ],
        ),
    ]
